#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

version: 2.1

commands:
  influxdb-onboarding:
    steps:
      - run:
          name: "Post onBoarding request to InfluxDB 2"
          command: ./bin/influxdb-onboarding.sh
  prepare:
    description: "Prepare environment to tests"
    steps:
      - checkout
      - influxdb-onboarding
  test:
    parameters:
      ruby-image:
        type: string
      gemspec-file:
        type: string
      path:
        type: string
    steps:
      - restore_cache:
          name: Restoring Gem Cache
          keys:
            - &cache-key gem-cache-{{ checksum "<< parameters.path >>/<< parameters.gemspec-file >>" }}-<< parameters.ruby-image >>
            - gem-cache-{{ checksum "<< parameters.path >>/<< parameters.gemspec-file >>" }}
            - gem-cache-
      - run:
          name: Install dependencies
          command: |
            cd << parameters.path >>
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - run:
          name: Static code analyze
          command: |
            cd << parameters.path >>
            bundle exec rake rubocop
      - run:
          name: Run tests
          command: |
            cd << parameters.path >>
            export MINITEST_REPORTER=JUnitReporter
            bundle exec rake test
      - save_cache:
          name: Saving Gem Cache
          key: *cache-key
          paths:
            - << parameters.path >>/vendor/bundle
          when: always
      - storing-test-results:
          path: << parameters.path >>
  storing-test-results:
    parameters:
      path:
        type: string
    steps:
      - store_test_results:
          path: << parameters.path >>/test/reports

jobs:
  tests-ruby:
    parameters:
      ruby-image:
        type: string
        default: &default-ruby-image "circleci/ruby:2.6-stretch"
      influxdb-image:
        type: string
        default: &default-influxdb-image "influxdb:v2.0.4"
      gemspec-file:
        type: string
        default: influxdb-client.gemspec
      path:
        type: string
        default: .
    docker:
      - image: << parameters.ruby-image >>
      - image: &influx-image quay.io/influxdb/<< parameters.influxdb-image >>
        environment:
          INFLUXD_HTTP_BIND_ADDRESS: :8086
    steps:
      - prepare
      - test:
          ruby-image: << parameters.ruby-image >>
          gemspec-file: << parameters.gemspec-file >>
          path: << parameters.path >>

  deploy-preview:
    docker:
      - image: *default-ruby-image
    parameters:
      gemspec-file:
        type: string
      path:
        type: string
    steps:
      - run:
          name: Early return if this build is from a forked repository
          command: |
            if [[ $CIRCLE_PROJECT_USERNAME != "influxdata" ]]; then
              echo "Nothing to do for forked repositories, so marking this step successful"
              circleci step halt
            fi
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh
      - run:
          name: Build a Gem bundle
          command: |
            cd << parameters.path >>
            gem build << parameters.gemspec-file >>
      - run:
          name: Deploy pre-release into https://rubygems.org
          command: |
            cd << parameters.path >>
            gem push influxdb-client-*.pre.$CIRCLE_BUILD_NUM.gem
workflows:
  version: 2
  build:
    jobs:
      - tests-ruby:
          name: client-r3.0
          ruby-image: "circleci/ruby:3.0-buster"
      - tests-ruby:
          name: APIs-r3.0
          ruby-image: "circleci/ruby:3.0-buster"
          gemspec-file: influxdb-client-apis.gemspec
          path: ./apis
          requires:
            - client-r3.0
      - tests-ruby:
          name: client-r2.7
          ruby-image: "circleci/ruby:2.7-buster"
      - tests-ruby:
          name: APIs-r2.7
          ruby-image: "circleci/ruby:2.7-buster"
          gemspec-file: influxdb-client-apis.gemspec
          path: ./apis
          requires:
            - client-r2.7
      - tests-ruby:
          name: client-r2.6
      - tests-ruby:
          name: APIs-r2.6
          gemspec-file: influxdb-client-apis.gemspec
          path: ./apis
          requires:
            - client-r2.6
      - tests-ruby:
          name: client-r2.6-nightly
          influxdb-image: "influxdb2:nightly"
      - tests-ruby:
          name: APIs-r2.6-nightly
          influxdb-image: "influxdb2:nightly"
          gemspec-file: influxdb-client-apis.gemspec
          path: ./apis
          requires:
            - client-r2.6-nightly
      - tests-ruby:
          name: client-r2.5
          ruby-image: "circleci/ruby:2.5-stretch"
      - tests-ruby:
          name: APIs-r2.5
          ruby-image: "circleci/ruby:2.5-stretch"
          gemspec-file: influxdb-client-apis.gemspec
          path: ./apis
          requires:
            - client-r2.5
      - tests-ruby:
          name: client-r2.4
          ruby-image: "circleci/ruby:2.4-stretch"
      - tests-ruby:
          name: APIs-r2.4
          ruby-image: "circleci/ruby:2.4-stretch"
          gemspec-file: influxdb-client-apis.gemspec
          path: ./apis
          requires:
            - client-r2.4
      - deploy-preview:
          name: Deploy Client
          gemspec-file: influxdb-client.gemspec
          path: .
          requires:
            - APIs-r3.0
            - APIs-r2.7
            - APIs-r2.6
            - APIs-r2.6-nightly
            - APIs-r2.5
            - APIs-r2.4
          filters:
            branches:
              only: master
      - deploy-preview:
          name: Deploy APIs
          gemspec-file: influxdb-client-apis.gemspec
          path: ./apis
          requires:
            - Deploy Client
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tests-ruby
