#
# The MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

version: 2.1

commands:
  influxdb-onboarding:
    steps:
      - run:
          name: "Post onBoarding request to InfluxDB 2"
          command: ./bin/influxdb-onboarding.sh
  prepare:
    description: "Prepare environment to tests"
    steps:
      - checkout
      - influxdb-onboarding
  test:
    parameters:
      ruby-image:
        type: string
    steps:
      - restore_cache:
          name: Restoring Gem Cache
          keys:
            - &cache-key gem-cache-{{ checksum "influxdb-client.gemspec" }}-<< parameters.ruby-image >>
            - gem-cache-{{ checksum "influxdb-client.gemspec" }}
            - gem-cache-
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - run:
          name: Static code analyze
          command: |
            bundle exec rake rubocop
      - run:
          name: Run tests
          command: |
            export MINITEST_REPORTER=JUnitReporter
            bundle exec rake test
      - save_cache:
          name: Saving Gem Cache
          key: *cache-key
          paths:
            - ./vendor/bundle
          when: always
  storing-test-results:
    steps:
      - store_test_results:
          path: test/reports

jobs:
  tests-ruby:
    parameters:
      ruby-image:
        type: string
        default: &default-ruby-image "circleci/ruby:2.6-stretch"
      influxdb-image:
        type: string
        default: &default-influxdb-image "influxdb:2.0.0-beta"
    docker:
      - image: << parameters.ruby-image >>
      - image: &influx-image quay.io/influxdb/<< parameters.influxdb-image >>
    steps:
      - prepare
      - test:
          ruby-image: << parameters.ruby-image >>
      - storing-test-results

  deploy-preview:
    parameters:
      influxdb-image:
        type: string
        default: *default-influxdb-image
    docker:
      - image: *default-ruby-image
      - image: *influx-image
    steps:
      - run:
          name: Early return if this build is from a forked repository
          command: |
            if [[ $CIRCLE_PROJECT_USERNAME != "influxdata" ]]; then
              echo "Nothing to do for forked repositories, so marking this step successful"
              circleci step halt
            fi
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh
      - run:
          name: Build a Gem bundle
          command: |
            gem build influxdb-client.gemspec
      - run:
          name: Deploy pre-release into https://rubygems.org
          command: |
            gem push influxdb-client-*.pre.$CIRCLE_BUILD_NUM.gem
workflows:
  version: 2
  build:
    jobs:
      - tests-ruby:
          name: ruby-2.7
          ruby-image: "circleci/ruby:2.7-buster"
      - tests-ruby:
          name: ruby-2.6
      - tests-ruby:
          name: ruby-2.6-nightly
          influxdb-image: "influx:nightly"
      - tests-ruby:
          name: ruby-2.5
          ruby-image: "circleci/ruby:2.5-stretch"
      - tests-ruby:
          name: ruby-2.4
          ruby-image: "circleci/ruby:2.4-stretch"
      - deploy-preview:
          requires:
            - ruby-2.7
            - ruby-2.6
            - ruby-2.6-nightly
            - ruby-2.5
            - ruby-2.4
          filters:
            branches:
              only: master

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tests-ruby
